### ISSUE TITLE
generating reports via confusion_matrix (not just via OOP)

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#100]
Right now reports can be generated only via ConfusionMatrix and not via confusion_matrix() - (use the OOP interface)

The purpose of [sklearn_evaluation.ClassifierEvaluator](https://docs.sklearn-evaluation.ploomber.io/en/latest/api/evaluator.html#sklearn_evaluation.ClassifierEvaluator) is to provide a simpler API where you can quickly plot and evaluate a model(s) and generate reports from them (right now the only way of generating reports is to use the OOP interface). Since the OOP is simpler, it also has some constraints. When plotting a confusion matrix from the plot module, you can pass a [matplotlib.axes.Axes](https://matplotlib.org/stable/api/axes_api.html#matplotlib.axes.Axes) object which gives you great flexibility, you can use this to plot a 2 x 2 grid with 4 confusion matrices for different models for example, or to customize the style and elements in the plot.

**Comment by edublancas** [comment]
This isn't possible without making big changes to the API. Functions return a matplotlib object, so there isn't anything else the user can do besides displaying the plot.

The OOP interface is more flexible, what sklearn did was to move from functions to OOP, I think we should do the same. but keep the functional API as legacy for backwards compatibility
