### ISSUE TITLE
Missing plot for ClassificationReport in the current docs

### ISSUE THREAD

**Issue by yafimvo** [ploomber/sklearn-evaluation#102]
There is an example [here](https://sklearn-evaluation.readthedocs.io/en/latest/api/plot.html#sklearn_evaluation.plot.ClassificationReport) of the `ClassificationReport` but the actual plot is missing.

@neelasha23 @idomic 
We should check if it persists after migrating to new docs.

**Comment by edublancas** [comment]
problem still there: https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html#classificationreport

**Comment by neelasha23** [comment]
Checking
