### ISSUE TITLE
remove SKLearnEvaluationLogger and use new logger in ploomber-core

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#105]
I updated the telemetry logger in ploomber-core, there is another implementation here that we should migrate to the one in ploomber-core to prevent duplication. the new logger hasn't been released yet, so I will tackle this once I release it

**Comment by idomic** [comment]
Please be more specific in the user story

**Comment by edublancas** [comment]
edited

**Comment by edublancas** [comment]
we're not: https://github.com/ploomber/sklearn-evaluation/blob/557ea67ac30afa01407fa0f30213325b16f61c20/src/sklearn_evaluation/plot/clustering.py#L63
