### ISSUE TITLE
Evaluating issues with different plots

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#113]
The most common one we could think of is the confusion matrix. 
We should add a feature to alert users when their plot is off, for instance if the matrix shows values below a certain level of false postives/negatives we should give a heads up to the user.

**Comment by edublancas** [comment]
See this for important details: https://github.com/ploomber/ploomber-engine/issues/20#issuecomment-1364365675

**Comment by edublancas** [comment]
This is a good use case for extending the OOP.

For example, we can implement a `.diagnose` method:

```python
from sklearn_evaluation import plot

cm = plot.ConfusionMatrix(..)

# displays some information
cm.diagnose()
```

The main challenge is to come up with some useful heuristics. But is per-plot diagnostics too detailed? (presumably, these will be diagnostics about the model, not necessarily about the plot)

Alternatively, we can do something like this:

```python
from sklearn_evaluation import diagnose

diagnose.classifier(random_forest)
```

And then, the heuristics in `diagnose.classifier` can decide the best plot to communicate the insights. e.g., if we find that there are too many false positives, we can show a confusion matrix. if calibration is a problem ,show a calibration curve.

I'm tilting towards the second option.
