### ISSUE TITLE
Better tracker integration precision-recall curve

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#117]
See issue below, apply for the titled plot
[See reference](https://github.com/ploomber/sklearn-evaluation/issues/84)

**Comment by neelasha23** [comment]
The refactoring was done. Are we not integrating with tracker?
@idomic

**Comment by edublancas** [comment]
I think @neelasha23 is referring to adding `log_precision_recall` to the tracker, I think it's a valid point. But I'm unsure if we should tackle it soon.

**Comment by neelasha23** [comment]
yes that's what I meant!
