### ISSUE TITLE
Better tracker integration Calibration curve

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#118]
See the issue below, apply for the titled plot
[Reference](https://github.com/ploomber/sklearn-evaluation/issues/84)

**Comment by edublancas** [comment]
@neelasha23: the PR is still pending review (so not yet in master), but I added some guidelines to spec the object-oriented API.

developer guide: https://sklearn-evaluation.ploomber.io/en/refactor/reference/developer.html
full example: https://github.com/ploomber/sklearn-evaluation/blob/refactor/src/sklearn_evaluation/plot/_example.py

**Comment by neelasha23** [comment]
Ok.so both PR and calibration needs to follow these new guidelines?

**Comment by edublancas** [comment]
there might be some small changes but yes.

These aren't new, we already implemented them but we didn't have them explicitly in an abstract class.

**Comment by neelasha23** [comment]
References to other pages are not working [here](https://sklearn-evaluation.ploomber.io/en/refactor/reference/developer.html). e.g., `AbstractPlot`, `MyBar`

**Comment by edublancas** [comment]
addressed this as well and pushed to the PR
