### ISSUE TITLE
add `SQLiteTracker.log_roc`

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#122]
Now that `plot.ROC` has been implemented, we can add `log_roc` to the experiment tracker. See the confusion matrix implementation for [an example](https://github.com/ploomber/sklearn-evaluation/blob/8414baaec836b0d17cf7614061f8dcfd93415d13/src/sklearn_evaluation/tracker.py#L63) and [classification report](https://github.com/ploomber/sklearn-evaluation/blob/8414baaec836b0d17cf7614061f8dcfd93415d13/src/sklearn_evaluation/tracker.py#L84)

please modify the example as well: https://sklearn-evaluation.ploomber.io/en/latest/comparison/SQLiteTracker.html

**Comment by idomic** [comment]
@edublancas can we close this?
