### ISSUE TITLE
Real-time tracking while fitting NN/deep learning

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#125]
If I'm training a model and allowing tracking, I should be able to open a new terminal and query the results in real-time (or at least see some of the parameters collected). This can happen every epoch on the network.

**Comment by edublancas** [comment]
this is already possible. since logs go to a sqlite database, you can open a new process and query it.

**Comment by idomic** [comment]
Right, what we're missing is a good example or a deep dive tutorial

**Comment by edublancas** [comment]
Makes sense. A typical use case is training a neural network and recording metrics on every epoch

**Comment by edublancas** [comment]
the tutorial should use our sqlitetracker: https://sklearn-evaluation.ploomber.io/en/latest/api/SQLiteTracker.html#sqlitetracker

**Comment by idomic** [comment]
@neelasha23 if one of the top ones is about computer vision or neural networks we can get 1 bird with 2 stones.

**Comment by neelasha23** [comment]
sure, will try this out
