### ISSUE TITLE
SKE: Chart as png for reports

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#130]
We should allow the user to export the plots, in case there is stake holders report to be made.
There should be a one-liner to export my designated plot.

---

owner: @edublancas

**Comment by edublancas** [comment]
An easy way to implement this would be to add a `to_png` method to the [AbstractPlot](https://github.com/ploomber/sklearn-evaluation/blob/master/src/sklearn_evaluation/plot/plot.py) class and grab the `self.figure_` attribute

**Comment by idomic** [comment]
@tonykploomber wanna take it?

**Comment by edublancas** [comment]
I'm assigning this to intern candidates

**Comment by tl3119** [comment]
I will try to do this

**Comment by edublancas** [comment]
assigned @tl3119!

**Comment by edublancas** [comment]
check out our contributing guide, but feel free to ask any questions! https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md

**Comment by tl3119** [comment]
I have read the whole plot.py file and serialize.py file, and now we want to add a to_png method to export any plots to the png file. 
I want to use `self.figure_savefig()` method to achieve the goal, and just make sure the format is png in this function.
Just want to make sure that is my idea correct, or do I miss anything?

**Comment by edublancas** [comment]
> I want to use self.figure_.savefig()

you're right, this is the way to go! please add this to AbstractPlot, then add some unit tests to check that the concrete classes (the classes that inherit from AbstractPlot) can execute the `to_png`  method and that the file exists after calling it

**Comment by tl3119** [comment]
Sure! I will do that!

**Comment by tl3119** [comment]
I have added a pull request! Please check!

**Comment by tl3119** [comment]
I found that PR run failed, is that the problem the test case doesn't work well? I tried to follow the contribution guide to make tests, but I met some problems in terminal. Could you tell me how should I execute the test to make sure that work?

**Comment by tonykploomber** [comment]
@tl3119 
You can use pytest to run the individual test. In your case:
`pytest tests/test_plot_to_png.py`

Also, seem the PR run failed is the lint issue, please refer to the [formatting section](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#lintingformatting)

**Comment by tl3119** [comment]
I have fixed the issue and submitted PR request, and all the tests pass now.
