### ISSUE TITLE
SKE: Adding a trend to scatterplots

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#131]
If I'm fitting an SVM for instance, I should be able to add lines, or even a trend line into a scatterplot.

**Comment by idomic** [comment]
[Another example](https://en.wikipedia.org/wiki/Local_regression)

**Comment by edublancas** [comment]
I'm not following this one. A scatterplot of what? (what's in the X and Y axis?)

**Comment by idomic** [comment]
It'd probably be your data, so pengiuns is X, Y is their species:

"Locally estimated scatterplot smoothing, or LOESS, is a nonparametric method for smoothing a series of data in which no assumptions are made about the underlying structure of the data. LOESS uses local regression to fit a smooth curve through a scatterplot of data."

**Comment by edublancas** [comment]
LOESS is a non parametric method for fitting data. And scatter plot is just referring to the input data, it's not that LOESS is a plot itself.

We can do a vanilla scatter plot but that's one line in matplotlib, there isn't much benefit to adding it. Unless we add extra things like coloring outliers or something else.

**Comment by idomic** [comment]
Yeah I guess it's an overkill.
