### ISSUE TITLE
SKE: Need to add python 3.11 support

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#141]
Our CI is currently python 3.7 - 3.10, we should add 3.11 to it and make sure the tests are passing.

**Comment by idomic** [comment]
Doesn't look [conda](https://repo.anaconda.com/pkgs/main/osx-arm64/) supports it atm.

**Comment by edublancas** [comment]
conda doesn't, but it'll work if we install form conda-forge

**Comment by idomic** [comment]
Yeah I saw that: `conda create --name py3.11 python=3.11 -c conda-forge`
The question if we want our CI to count and be based on conda-forge

**Comment by edublancas** [comment]
conda-forge is pretty reliable, we are using it heavily
