### ISSUE TITLE
`silhouette_analysis` plot improvements

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#150]
here are some things we can improve in the `silhouette_analysis`

- silhouette_analysis_from_results should not be part of the public API since it's method that it's used as an intermediate step, so we should rename it to something like `_silhouette_analysis`. I think this computes silhouettes for a single cluster so maybe `_silhouette_analysis_one_cluster`

- `silhouette_analysis` had a hardcoded figure size (which I already removed); however, to make the tests pass, I had to move this hardcoded figure size to the tests, we should remove this

**Comment by neelasha23** [comment]
`silhouette_analysis_from_results` was added to be consistent with `elbow_curve_from_results` (user wants to generate plots from custom model). Do we need to make `elbow_curve_from_results` internal too?
