### ISSUE TITLE
`elbow curve` should have index to describe the lines

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#152]
An index to state what's the blue line and what's the green dotted one is currently missing.
<img width="722" alt="Screen Shot 2022-12-29 at 10 12 56 AM" src="https://user-images.githubusercontent.com/11596985/209972776-d8a7a150-36d4-47c3-ac36-350ab9eb589b.png">

**Comment by edublancas** [comment]
tip: this can easily be added by calling `ax.legend()`
