### ISSUE TITLE
prediction error plot to support pandas Series object

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#154]
When reading dataset as a pandas dataframe, the prediction error plot throws error `AttributeError: 'Series' object has no attribute 'reshape'`.
This code can solve the issue:
```
    if isinstance(y_true, pd.Series):
        y_reshaped = y_true.values.reshape((-1, 1))
    else:
        y_reshaped = y_true.reshape((-1, 1))
```

Additionally add test case for dataframe input.

**Comment by edublancas** [comment]
so the problem is that predicton_error supports numpy arrays but not pandas.Series, right?

would calling `.values` on the series object to get the underlying numpy aray work? sounds simpler than the solution you're proposing
