### ISSUE TITLE
Cooks distance plot improvements

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#156]
Hovering over the plot should display the exact instance index so that user can further inspect this point. Currently it is not clear from the plot.

**Comment by edublancas** [comment]
great point! I think the main challenge here is that matplotlib does not support hovering out of the box. I did some quick research and there is this [package](https://mplcursors.readthedocs.io/en/stable/examples/hover.html) to support it. But looks new and I'm wary of adding these kinds of dependencies.

Another alternative would be to support alternative plotting backends, for example, plotly, which produces plots with JS, which allows us to add interactivity. I like this second approach better.

**Comment by idomic** [comment]
Yeah I think having the flexibility is worth it, it kind of encompasses the first point in it.
