### ISSUE TITLE
Add get started button

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#160]
There should a button to get started from the repo, just like ploomber.

**Comment by WSShawn** [comment]
need a .ipynb file to launch the binder

**Comment by idomic** [comment]
@edublancas do we want to direct to classification at first?
I don't see a point direction to the `readme.md` since it's not interactive

**Comment by edublancas** [comment]
we can launch from `.md`

here's a sample URL: https://binder.ploomber.io/v2/gh/ploomber/sklearn-evaluation/master?urlpath=lab/tree/docs/quickstart/classification.md

**Comment by edublancas** [comment]
and yeah, maybe let's redirect to classification.md - so just use the link I shared

**Comment by idomic** [comment]
Implemented, closing
