### ISSUE TITLE
Content nav bar links aren't correctly marked

### ISSUE THREAD

**Issue by yafimvo** [ploomber/sklearn-evaluation#165]
The content navigation bar doesn't mark the proper link when clicking a link

https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html#confusionmatrix

Click on Rank2D should mark Rank2D

![image](https://user-images.githubusercontent.com/103026689/210529094-a69796c9-3637-46da-91b1-9659195912b1.png)

**Comment by edublancas** [comment]
this is a problem with the [sphinx-book theme](https://github.com/executablebooks/sphinx-book-theme/issues/545). there's already a PR waiting to be merged

**Comment by edublancas** [comment]
closing this since it belongs to another repo
