### ISSUE TITLE
split API section into functional and object-oriented

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#172]
we currently have a listing of all our `plot` API in  a single section: https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html

I think it'd be better to split it in functional and object-oriented

```
object-oriented
----------------

ROC
ConfusionMatrix
...

functional
----------

roc
confusion_matrix
...


```

We should also use the [seealso](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-seealso) directive to link from roc <-> ROC and all others. 

Furthermore, we need to explain that the functional API is the easiest to get started, but the object-oriented one offers more flexibility to compare models

**Comment by edublancas** [comment]
Note: I'm suggesting re-organize the current file, not break this into multiple secions

**Comment by idomic** [comment]
Add the image for reference, worth 1000 words.

**Comment by edublancas** [comment]
currently it's mixed: some oop, some functions, then oop again:

![image](https://user-images.githubusercontent.com/989250/211046212-cd6c6b6c-dc35-4db3-a363-91f926ba3db1.png)


at the top, we should also include a brief description of what's the difference so users know what to use

**Comment by idomic** [comment]
It should probably be under one title i.e:
**Confusion Matrix**: and then in it there should be a section for each pattern - OOP, static (functional is also a bit confusing IMO). There's no point of showcasing everything in the menu as it's pretty confusing.

**Comment by edublancas** [comment]
all plots listed is common practice because it allows you to do ctrl+f and type what you want. otherwise people have to find out that `confusion_matrix` is under `ConfusionMatrix`

**Comment by idomic** [comment]
So separating but still keeping the actual call for each?

**Comment by edublancas** [comment]
like my initial comment. two sections (cannot think of other name rather than functional, but we can change it), each plot or class listed there:

```
{some short paragraph describing the differences, and link to the OOP vs function document where we explain more details} 

functional
----------

roc
confusion_matrix
...

object-oriented
----------------

ROC
ConfusionMatrix
...
```

all should  be visible from the right bar (roc, confusion_matrix, ROC, ConfusionMatrix)


we can add `See Also` links so people can move between confusion_matrix <> ConfusionMatrix
