### ISSUE TITLE
track_execution parameters should be optional.

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#181]
When trying to run a command without specifying the parameters argument an error is thrown.
i.e.

`track_execution("pycaretBinary.ipynb", quiet=True, database="pycaret.db")`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_9979/753018148.py in <cell line: 1>()
----> 1 track_execution("fit.py", quiet=True, database="pycaret.db")

~/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py in wrapper(*args, **kwargs)
    674                         result = func(_payload, *args, **kwargs)
    675                     else:
--> 676                         result = func(*args, **kwargs)
    677                 except Exception as e:
    678 

TypeError: track_execution() missing 1 required positional argument: 'parameters'
```

The workaround was passing `parameters={}`, but then it prints some weird output: `Could not find block with the # parameters comment`.

We should make parameters optional, and set to empty by default so users don't need to take this workaround.

**Comment by edublancas** [comment]
this should be opened in ploomber-engine

**Comment by idomic** [comment]
Closed, moved to https://github.com/ploomber/ploomber-engine/issues/30
