### ISSUE TITLE
incorrect elbow_curve results 

### ISSUE THREAD

**Issue by yafimvo** [ploomber/sklearn-evaluation#192]
```
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

from sklearn_evaluation import plot

X, _ = make_blobs(n_samples=100, centers=3, n_features=5, random_state=0)
kmeans = KMeans(random_state=1, n_init=5)

plot.elbow_curve(X, kmeans, range_n_clusters=range(1, 30))
plt.show()
```
![image](https://user-images.githubusercontent.com/103026689/212099689-07957165-4abc-4605-a49b-fca5a7dbc85b.png)

this should plot the following result

![image](https://user-images.githubusercontent.com/103026689/212102207-006b8bf7-a3de-4aa4-a81d-f196eacad697.png)

**Comment by idomic** [comment]
@yafimvo can we close this?

**Comment by edublancas** [comment]
ran this on binder and got the right result:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/989250/215506914-d2fc00cb-ab93-4b4a-abc7-26e95ac7ebd0.png">


closing
