### ISSUE TITLE
Missing tutorial: feature importance and normalization

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#199]
This guide should cover feature importance and feature normalization.
It can help with performance in a few models, but in others it has no effect, we should explain why.

**Comment by edublancas** [comment]
maybe feature selection? It's more general. we can include things such as using feature importance, and algorithms for feature pruning

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/sklearn-evaluation/issues/287
