### ISSUE TITLE
adding description to each example / splitting them into each use case

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#217]
most of our example have no descriptions or describe the steps as comments within the code. [see example here](https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html#confusionmatrix).

It'd be better if we had a description for each one so users know what each example is doing. Also, many of our examples are actually doing many things at once and It'd be better if they only did one thing (so we can come up with a concise description)

for example, for confusion matrix, we could do

```
confusion matrix for binary classifier:
[example]

confusion matrix for multi-class classifier:
[example]


compare confusion matrix of two binary classifiers:
[example]

find the difference between confusion matrices of two binary classifiers:
[example]

compare confusion matrix of two multi-class classifiers:
[example]

find the difference between confusion matrices of two multi-class classifiers:
[example]
```

I think this will work:

```
Examples
----------

description...

.. plot:: path/to/example.py

another...

.. plot:: path/to/another.py

```

**Comment by ShubhamGawande191** [comment]
Hey, assign me #217. Also, could you let me know exactly what I need to do? For example, do I add comments to each available example? If so, do I also add links to say make_classification?

**Comment by edublancas** [comment]
it's just adding descriptions to each example, no need to add links.

in the source code, you'll see stuff like this:

```
Examples
----------

.. plot:: path/to/file.py

```

We need to add descriptions:


```
Examples
----------

Some short description:

.. plot:: path/to/file.py

```

Descriptions should be 1-2 sentences, so you need to read the example, see what it's doing and add the description, if you have questions about what some examples are doing, feel free to ask
