### ISSUE TITLE
researching good defaults for grids

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#229]
@yafimvo is working on a new feature to help users optimize model hyperparameters(https://github.com/ploomber/sklearn-evaluation/pull/215); we defined some [defaults](https://github.com/ploomber/sklearn-evaluation/pull/215#pullrequestreview-1263708956) for now, based on a [blog post](https://towardsdatascience.com/how-to-tune-a-decision-tree-f03721801680), that cites a [paper](https://arxiv.org/abs/1812.02207), but we'd like to do more research.

- first, we must dive deeper into the blog post and paper I shared above to define sensible defaults for a random forest grid search. Then, we'd like to look for other resources to see if we find more information
- we can repeat the same process for other models. I think we can start with XGBoost or logistic regression since those are the most popular models in ML

cc @idomic @WSShawn

**Comment by WSShawn** [comment]
@idomic Working on the XGBoost defaults right now. Do we only want a set of good default values or is there anywhere I can update the code with these values also? I can see in #215 that there is a file for grid values but I could not find it in the repo. Please clarify. Thanks!

**Comment by idomic** [comment]
For the latter part check [this one out](https://github.com/ploomber/sklearn-evaluation/blob/20ae8ebfc449df54c18ce87fce988317d57d2d16/src/sklearn_evaluation/grid/classifier_grid.py#L5).

**Comment by WSShawn** [comment]
Got it! Working on XGBoost tonight, I'll share my conclusions and reference here later.

**Comment by WSShawn** [comment]
Reference: https://medium.com/broadhorizon-cmotions/hyperparameter-tuning-for-hyperaccurate-xgboost-model-d6e6b8650a11#:~:text=Typically%20used%20values%20are%200.4,its%20default%20value%20is%201

Conclusions: 
- Learning_rate (eta): 0.01 - 0.3 with default at 0.3, in the cited example, grid is [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3]
- N_estimators: any integer larger than 0, the larger the integer, the more accurate trainset performance, with default at 100, in the cited example, grid is [50, 500, 50]
- Max_depth: 3 - 10 with a default of 6 is very typical, in the cited example, grid is [3,10, 2]
- Min_child_weight: can be any number. default is 1, in the cited example, grid is [1, 6, 2]
- Subsample: typical value 0.4 - 1 with a default of 1, in the cited example, grid is [0.4, 1, 0.1]
- Colsample_bytree: any number in 0.4 - 1, default is usually 1, in the cited example, grid is [0.4, 1, 0.1]
- Gamma (min_split_loss): any integer, usually default is 1, in the cited example, grid is [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
- Lambda: any integer, usually default is 1, in the cited example, grid is [0, 0.5, 1, 1.5, 2, 3, 4.5]

**Comment by WSShawn** [comment]
Please leave comments so that I know if I am getting the right conclusions that we want. Thanks!

**Comment by idomic** [comment]
It's great, seems we were also in the right direction.
Let's add logistic regression here as well?
Once that's here, you can go ahead and open a PR to revise the defaults and ranges accordingly.

**Comment by WSShawn** [comment]
got it! working on it.

**Comment by edublancas** [comment]
also, if we can find some peer-reviewed papers, that'd be great! because medium posts might not be rigorous

**Comment by WSShawn** [comment]
ok!

**Comment by WSShawn** [comment]
> It's great, seems we were also in the right direction. Let's add logistic regression here as well? Once that's here, you can go ahead and open a PR to revise the defaults and ranges accordingly.
> 
> Also, upon checking Gamma, seems like the default value there is 0 and not 1, please double check that the values actually match. `Gamma can be any integer and its default value is 0.`

yes you are right, I'll fix it to 0

**Comment by WSShawn** [comment]
Update on Logistic regression: I'm still working on finding some more rigorous documents but these are by far the most direct source indicating default parameter values for the model.

Source:
https://towardsdatascience.com/logistic-regression-model-tuning-with-scikit-learn-part-1-425142e01af5 gives a brief range for grid search values of the following parameters: 
C: logspace(-4, 4, 20)
penalty: [‘l1’, ‘l2’]
n_estimators: [10, 101, 10]
max_features: [6, 32, 5]

Source: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html gives some default values for the following parameters:
tol: 1e-4
C: 1
intercept _scaling: 1

Please let me know if we are good to revise the grid search code and open the PR.

**Comment by edublancas** [comment]
> C: logspace(-4, 4, 20)
> penalty: [‘l1’, ‘l2’]
> n_estimators: [10, 101, 10]
> max_features: [6, 32, 5]

these ones look like mix a few models? penalty is for logistic regression, but n_estimators and max_features for random forest?

**Comment by WSShawn** [comment]
good catch. This post suddenly started to talk about random-forest classifier and I got confused. I'll redo this part tonight.

**Comment by edublancas** [comment]
any updates on this?
