### ISSUE TITLE
missing argument in __sub__

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#236]
we're not implementing `__sub__` in the plots. [example](https://github.com/ploomber/sklearn-evaluation/blob/20ae8ebfc449df54c18ce87fce988317d57d2d16/src/sklearn_evaluation/plot/roc.py#L234), but we're raising an exception so users explicitly know it won't work.

however, the signature is incorrect; we're missing one argument. otherwise, we get this error (instead of the NotimplementedError one):

```
__sub__() takes 1 positional argument but 2 were given
TypeError: __sub__() takes 1 positional argument but 2 were given
```

to simplify things, we should remove `__sub__` implementations from concrete classes to the `AbstractPlot` class so all plots inherit from it

**Comment by WSShawn** [comment]
do we also want this in AbstractComposedPlot ? Thanks!

**Comment by edublancas** [comment]
yes, also in AbstractComplosedPlot!

**Comment by WSShawn** [comment]
got it! Making PR for this one tomorrow the first thing!

**Comment by WSShawn** [comment]
@edublancas Question: after we move the __sub__ to AbstractPlot and AbstractComposedPlot classes, do we want to call "@SKLearnEvaluationLogger.log()" in  plot.py? Also I noticed that for confusion matrix, we actually defined an inheritance class for it following the AbstractComposedPlot class and the plot type we currently use is heatmap for the matrix. Does this mean I need to figure out how to include different plot types for for example elbow_curve and other inheritance plot class? Thanks!

**Comment by edublancas** [comment]
Sounds like you misunderstand what's required. there should be no changes to the telemetry. the only change is

> we should remove __sub__ implementations from concrete classes to the AbstractPlot class so all plots inherit from it

so anything that inherits from Abstract plot, has a `__sub__` raising a not implemented error should have the `__sub__` method removed.

then, we add `__sub__` to AbstractPlot and write a generic method there, again, raising a not implemented error

**Comment by edublancas** [comment]
try opening a draft PR so I can submit more precise feedback
