### ISSUE TITLE
improvements to ROC composed plot

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#237]
when creating a multi-class ROC, we display labels like this:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/989250/214451492-f9114e01-518c-4c64-a65e-92e75047564f.png">

and when creating a composed plot, it'll look like this:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/989250/214451542-e7ecc963-5285-4b5b-be4e-1ce4cce9a032.png">

the problem is that it's hard to know which curves came from which original plot. I suggest the following:  change the patterns so all the lines from the first plot look different from the second one (perhaps the first group can be a continuous line while the second a dotted line (- - - -)

**Comment by idomic** [comment]
I like this.
What about the fact that the index takes half the size of the plot, making it difficult to read?

**Comment by edublancas** [comment]
There is an option to show the label box outside the plot; that sounds like the best option

**Comment by idomic** [comment]
Both
