### ISSUE TITLE
extensions to the precision recall curve

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#239]
this sklearn example has a few interesting things like the the iso-f1 curves and micro-average precision-recall, we should have those as well: https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html#sphx-glr-auto-examples-model-selection-plot-precision-recall-py

**Comment by idomic** [comment]
@edublancas please add an explanation of what needs to be done.

**Comment by edublancas** [comment]
> the iso-f1 curves and micro-average precision-recall,

add this

**Comment by idomic** [comment]
This task is about adding those new curve metrics to our existing ske
