### ISSUE TITLE
improve PCA Plots

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#254]
The following plots can be good additions to the basic PCA plot:
1. Scree plot
2. Loading plot
3. Biplot

**Comment by edublancas** [comment]
> Scree plot

Is this the same as elbow_curve, except with a different metric? if so, we can re-use the implementation or at least parts of it. the question then is if we want to have two plotting functions or just one with a `metric` parameter.


also, for the basic plot, we can add the eigenvectors: https://stackoverflow.com/questions/54644957/how-to-plot-largest-and-smallest-eigen-vectors-for-2-dimensional-data-using-num
