### ISSUE TITLE
clean up examples

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#270]
While working on https://github.com/ploomber/sklearn-evaluation/pull/269, we realized [some of our examples](https://github.com/ploomber/sklearn-evaluation/blob/665bc60c8170b8e19b1191161af2145751eed72b/examples/roc.py#L19) have variables that aren't used. The lines were already commented out but it'd be better to delete them.

I think we can also remove calls to [`plt.show()`](https://github.com/ploomber/sklearn-evaluation/blob/665bc60c8170b8e19b1191161af2145751eed72b/examples/roc.py#L25)

**Comment by edublancas** [comment]
wanna tackle this @ShubhamGawande191? 😁

**Comment by ShubhamGawande191** [comment]
I would love to, but I would be busy for a few weeks, making it harder for me to contribute. If anyone else wants to take up the issue, I will add the names of some of the files in which I found the variables that aren't being used:
precision_recall_multiclass.py
precision_recall.py
roc_binary_classification.py
roc_comparison.py
roc_new_api.py
roc.py

**Comment by edublancas** [comment]
no worries, thanks a lot for your contribution!
