### ISSUE TITLE
SQLiteTracker upsert improvements

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#274]
Consider an experiment that contains a record `{"param1" :[1,2,...], "param2" " [3,4,5]}`. 
There can be an additional action `upsert_append` , in which if we upsert `{param1: 3}`  the value 3 will get appended to the existing list in key `param1` instead of replacing the entire list value.

**Comment by edublancas** [comment]
makes sense, this would be especially useful for neural networks, whose metrics are recorded over epochs.

**Comment by mehtamohit013** [comment]
Hi, I would like to work on this issue (as part of the interview process)

**Comment by edublancas** [comment]
assigned!

**Comment by mehtamohit013** [comment]
@edublancas Do you want a separate function ```upsert_append``` for this or modification to ```upsert``` with some additional parameter like ```mode='append'``` and ```mode='replace'```?
