### ISSUE TITLE
orgs reorganization: classification

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#283]
The documentation is becoming messy, so we need to re-organize it.

The classification section has the following sub-sections:

1. basic plots (old tutorial using functional API)
2. compare classifiers (recent tutorial, using object-oriented API)
3. evaluating classifiers (recent tutorial, with tools not covered in the other sections)
4. class imbalance (plots for class imbalance)
5. grid search (`RandomForestClassifierGrid`)
6. calibration (tutorial on probability calibration)

I suggest consolidating it into this:

1. Evaluation (how do I evaluate a classifier? show the most common plots: confusion matrix, classification report, ROC, and precision-recall)
2. Comparison (how do I compare two classifiers? show the same plots as above but the composed versions that allow comparing two models)
3. Optimization (how do I ensure the best performance?)
4. Tracking (how do I track experiments?)
5. Reporting (how do I generate a model evaluation report?)
6. Class imbalance
7. Calibration

## 1. evaluation

we can take the existing content from "basic plots". The objective is to have the most common plots and descriptions for each and use the new object-oriented API. We'll no longer include the functional API in the tutorials (except when a given plot only has a functional implementation) but we'll keep them in the API docs.

## 2. comparison

we can use the content from "compare classifiers". here we include the same plots as in "1. evaluation", except we show how to create the composed plots with `a+b` and `a - b`.

## 3. Optimization

we can move this [existing content](https://sklearn-evaluation.ploomber.io/en/latest/optimization/grid_search.html), and also include the content of [this](https://sklearn-evaluation.ploomber.io/en/latest/classification/grid_search.html), but shorten it so this section doesn't end up too long

## 4. tracking

we can use this [existing content](https://sklearn-evaluation.ploomber.io/en/latest/comparison/SQLiteTracker.html). but let's create a shorter version of the existing content. the idea is that the "tracking" tutorial under the "classification" section should be a short tutorial, and the existing, generic "tracking tutorial" should contain a deep dive into the features, we should also link from the former to the latter

## 5. reporting

move the [existing content](https://sklearn-evaluation.ploomber.io/en/latest/comparison/report.html)

## 6. class imbalance and 7. calibration

use existing content

## evaluating classifiers

Unsure about what to do about [this one](https://sklearn-evaluation.ploomber.io/en/latest/classification/evaluate.html); these aren't common plots, so I think we can remove the tutorial and move the content to the API docs.

---

thoughts on this, @neelasha23?

**Comment by neelasha23** [comment]
I missed the tag earlier.

I think Calibration curve should fit in along with classifier evaluations. I'll add more points once I start working on this.

**Comment by edublancas** [comment]
great!
