### ISSUE TITLE
confusion matrix compare plots improvement

### ISSUE THREAD

**Issue by neelasha23** [ploomber/sklearn-evaluation#286]
![compare_9_0](https://user-images.githubusercontent.com/29096135/218460442-7cda0d4b-d842-44ec-8093-0dea46be8ebd.jpeg)
These numbers are a bit confusing if user is looking at this chart directly and not the individual charts used to create this combined plot. 
Maybe we should be more explicit about which number represents Model 1 and which Model 2.

**Comment by edublancas** [comment]
agree. how do you think we could label them? perhaps a box with a diagonal and labels outside the matrix?

**Comment by neelasha23** [comment]
I think on the side opposite the True Label we can have
```
Model 1
Model 2
```
next to every cell.
