### ISSUE TITLE
add a tutorial on feature selection

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#287]
We should add a tutorial on feature selection, we can use the methods implemented in sklearn and complement it with our feature importance plot.

Quickly describe what feature selection is, what some methods are, and show some code snippets showing how to use sklearn for feature selection.

**Comment by bbeat2782** [comment]
When I'm ready, should I submit my .md file to the PR I created yesterday?

**Comment by edublancas** [comment]
whatever is easier for you, you can either modify the existing PR or close the old one and open a new one

**Comment by bbeat2782** [comment]
> whatever is easier for you, you can either modify the existing PR or close the old one and open a new one

Okay. Thanks for the answer and giving me the guideline for my initial feedback request

**Comment by edublancas** [comment]
fixed in https://github.com/ploomber/sklearn-evaluation/pull/304
