### ISSUE TITLE
docs building and CI taking too long

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#311]
the doc building process is taking too long. it used to take <10 mins but now it takes >20, my guess is that one of our recently tutorials is too slow and we merged it without realizing it

**Comment by neelasha23** [comment]
might be the tensorflow installation also.

**Comment by edublancas** [comment]
> might be the tensorflow installation also.

I looked at the build logs, the whole dependency installation is taking 1min, so the problem is when building the docs

**Comment by edublancas** [comment]
in jupyter-book 0.14, the runtime of each notebook is printed, this will help us find which notebook is taking too long: https://github.com/ploomber/contributing/issues/35

**Comment by edublancas** [comment]
I also noticed that the CI is taking too long as well (30 mins)

**Comment by edublancas** [comment]
5 examples were taking 2.5 mins each, fixed in #322

**Comment by edublancas** [comment]
> Are the examples in our out right now?
not following the question
