### ISSUE TITLE
Add Information Value and decile analysis using Lift Chart

### ISSUE THREAD

**Issue by adityajn105** [ploomber/sklearn-evaluation#32]
It will be a lot more helpful for fellow data scientist, if these two functionalities can be added. 

Information value: 
http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/

**Comment by edublancas** [comment]
we've implemented lift curve: https://sklearn-evaluation.ploomber.io/en/latest/api/plot.html#lift-curve
