### ISSUE TITLE
Add Model Comparison Functionality to NotebookCollection

### ISSUE THREAD

**Issue by hcho1111** [ploomber/sklearn-evaluation#46]
Model comparability with the `plot` argument of a `NotebookCollection` object could be improved. 

At the moment, models must be cycled through in order to compare plots. See documentation [here](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/NotebookCollection.html) for example. Perhaps it would benefit to add additional functionality that allows side by side comparisons, similar to that described in the advanced matplotlib usage guide [here](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/matplotlib.html). 

Things to consider: limitations on the number of models that can be plotted simultaneously (formatting issues), whether plotting models simultaneously is affected by window size, the degree to which the quality of individual plots is affected (if axes/labels/symbols get too small, perhaps we could reevaluate the inputs to improve visibility/model quality).

**Comment by edublancas** [comment]
this is a great idea. I actually released something like this, but only implemented it for confusion matrix: https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/compare.html

the idea is that to compare two models you could do:

```
# plot for model one
plot_one = ...

# plot for model two
plot_two = ...


# compare models in a single plot
plot_one + plot_two
```

We could implement the same logic for the other plots we have, and then incorporate that into NotebookCollection. thoughts? Do you want to give this a try?

**Comment by idomic** [comment]
@hcho1111 let's take this right after the blog is ready to publish

**Comment by edublancas** [comment]
we implemented some of these features as part of the `plot` module
