### ISSUE TITLE
Add new module: Regression

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#51]
We need to create a module for regression plots (can leverage the existing layout from [classification](https://github.com/ploomber/sklearn-evaluation/blob/master/src/sklearn_evaluation/plot/classification.py))

**Comment by edublancas** [comment]
Updates:

added a contributing.md with some guidelines: https://github.com/ploomber/sklearn-evaluation/blob/master/CONTRIBUTING.md

we can get started with the ones that appear here: https://www.scikit-yb.org/en/latest/oneliners.html#regression

**Comment by shizuchanw** [comment]
> Updates:
> 
> added a contributing.md with some guidelines: https://github.com/ploomber/sklearn-evaluation/blob/master/CONTRIBUTING.md
> 
> we can get started with the ones that appear here: https://www.scikit-yb.org/en/latest/oneliners.html#regression

Thank you!

**Comment by edublancas** [comment]
we have some regression plots, we can close this (and open issues for specific plots)
