### ISSUE TITLE
grid_search error log should be more specific

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#53]
The exception log is saying `som_param_rf_n_estimators is not a valid parameter`, it should imply what are the valid parameters and how the user can move on with the evaluation.

**Comment by idomic** [comment]
`plot.grid_search(clf.cv_results_, change='n_estimators', kind='bar')`, same happens with unsupported `kind`

**Comment by idomic** [comment]
@edublancas how can we make the error explicit and informative? Probably we'd also want to offer a solution/path to success here

**Comment by edublancas** [comment]
I wrote this code many years ago but I think this:

> The exception log is saying som_param_rf_n_estimators is not a valid parameter, it should imply what are the valid parameters and how the user can move on with the evaluation.

means the passed parameter does not exist. so we could change to "X does not exist, valid params are Y, and Z"

Same here:

> lot.grid_search(clf.cv_results_, change='n_estimators', kind='bar'), same happens with unsupported kind

we could say:

bar is not a valid value for the "kind" parameter, valid values are X, Y, Z.

These are pretty common validations, I suggest we add them to ploomber-core so we can run them in any package. I wrote some of these functions already in ploomber, we can migrate them from there.

**Comment by idomic** [comment]
Sure let's take this approach.

**Comment by edublancas** [comment]
took a look at ploomber's codebase. Looks like this is the only [validation function](https://github.com/ploomber/ploomber/blob/master/src/ploomber/util/validate.py) we have. we can migrate it to ploomber-core, then use it here

**Comment by idomic** [comment]
We should also include the built in python typo functionality as part of this issue.
