### ISSUE TITLE
Plot: Add slihouette plot

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#57]
We need to add the [plot](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html) and [score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html)

**Comment by idomic** [comment]
1. But for the silhouettes it is covered for 2+ clusters? I also think we should try to put the time while we're at it on the clustered data plots since it usually [comes together](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html#sphx-glr-auto-examples-cluster-plot-kmeans-silhouette-analysis-py).
2. I think the score is good enough for now in addition to the plots.

**Comment by neelasha23** [comment]
> 1. But for the silhouettes it is covered for 2+ clusters? I also think we should try to put the time while we're at it on the clustered data plots since it usually [comes together](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html#sphx-glr-auto-examples-cluster-plot-kmeans-silhouette-analysis-py).

yes it will work for 2+ clusters if number of features <=2. When features>2 we would need to plot a multi-dimensional plot I think. I'll check what options are there

**Comment by idomic** [comment]
Check out if sklearn supports it?

**Comment by edublancas** [comment]
> I have not added the visualization for clustered data plot as shown [here](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html) since it would get complicated when features > 2. If it's needed I can spend more time on it.

Here you're referring to the scatter plot, right? I don't think we need that anyway, we can just focus on the silhouette plot.

> Do we need to add anything elaborate with regards to the silhouette score? As of now there is call to the sklearn silhouette_score as in 

We don't need to implement the score since it's already on scikit-learn

**Comment by neelasha23** [comment]
Completed as part of this [PR](https://github.com/ploomber/sklearn-evaluation/pull/87)
