### ISSUE TITLE
Docs: Code snippet fix on classifiers

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#58]
[In here](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/classifier.html), the cells don't copy the notebook execution [10], in some of the cells it also includes the output [11]/[15]. It should be separated so it doesn't break the code.

**Comment by edublancas** [comment]
I wrote this documentation a while ago. I think our best option now is to move to jupyter book since it has much better support for notebooks

**Comment by idomic** [comment]
Closing as done, feel free to open if needed
