### ISSUE TITLE
readme example link broken

### ISSUE THREAD

**Issue by shizuchanw** [ploomber/sklearn-evaluation#61]
In sklearn-evaluation/README.md, features section, the report [example](http://htmlpreview.github.com/?https://github.com/edublancas/sklearn-model-evaluation/blob/master/examples/report.html) link in the second bullet point is broken.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/50822201/198415000-a051aa64-98f1-408c-be3c-d652c692fe5a.png">

**Comment by edublancas** [comment]
fixed, thanks!
