### ISSUE TITLE
Building docs: requirements.txt missing

### ISSUE THREAD

**Issue by shizuchanw** [ploomber/sklearn-evaluation#62]
In sklearn-evaluation/docs/README.md, it mentions 

> # Building docs
> Install requirements:

```
pip install -r requirements.txt
```

But there's no requirements.txt in this repo.

**Comment by edublancas** [comment]
right,

I think this should work (note that this requires conda):

```
pip install invoke
invoke setup
```

can you give it a try? if it works, please open a PR with the updated instructions

**Comment by shizuchanw** [comment]
> right,
> 
> I think this should work (note that this requires conda):
> 
> ```
> pip install invoke
> invoke setup
> ```
> 
> can you give it a try? if it works, please open a PR with the updated instructions

It worked: 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/50822201/198419548-f2357a3c-c079-46ce-90c1-bcdc5144799e.png">


Opening a PR right now :)
