### ISSUE TITLE
Bug: Missing colab flag

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#65]
on some of the stats calls, the colab flag is missing. This makes it difficult to understand how many of the users are actually in colab or just plain docker.

**Comment by edublancas** [comment]
this is most likely an error in https://github.com/ploomber/core but let's keep it here since we're unsure

**Comment by yafimvo** [comment]
I ran `sk-eval` locally after setting a new env variable "COLAB_GPU" to pass this check (from ploomber-core)
```
def is_colab():
    """Returns: True for Google Colab env"""
    return "COLAB_GPU" in os.environ
```
It created the following log:

```
        "metadata": {
            "action": "feature_importances",
            "feature": "plot",
            "args": {
                "top_n": null,
                "feature_names": null,
                "orientation": "horizontal",
                "ax": null
            },
            "colab": true
        },
```

Is it possible that this flag has not been invoked yet?

**Comment by idomic** [comment]
It's possible, I've played with the COLAB_GPU flag on the notebook, perhaps this is a better way of checking it:

```
try:
  import google.colab
  print("In colab")
except:
  print("No colab")
```

**Comment by edublancas** [comment]
I checkd on colab and the COLAB_GPU flag does not appear. I remember seeing that Colab changed the environments recently so probably the environment variable went away. I think we should go with @idomic's suggestion

**Comment by edublancas** [comment]
please update ploomber-core @yafimvo

**Comment by yafimvo** [comment]
added a PR to core

[link](https://github.com/ploomber/core/pull/17)
