### ISSUE TITLE
update sqlitetracker docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#74]
as part of the new [experiment tracker](https://ploomber.io/blog/experiment-tracking/) we made some improvements to SQLiteTracker, which remain undocumented. We should ensure that the new methods have docstrings and that the tutorial shows the new features.

to know what changed, check out the blog post: https://ploomber.io/blog/experiment-tracking/
and the changes to the source code: https://github.com/ploomber/sklearn-evaluation/blame/master/src/sklearn_evaluation/tracker.py

once that's documented, we should post it on socials, please include a GIF.

@RodolfoFerro: please add this to your tasks for the nov 21-25 week.

**Comment by RodolfoFerro** [comment]
TODO:
- Review git history to verify if Docstrings are needed
- Document in the docs notebook these changes

**Comment by RodolfoFerro** [comment]
This was documented in release 0.8.2.
