### ISSUE TITLE
minor changes to silhouette_plot

### ISSUE THREAD

**Issue by edublancas** [ploomber/sklearn-evaluation#86]
I was going to release a new version with the silhouette_plot @neelasha23 but noticed a few things.

Our convention is not to include the word `plot` in the function names (since they're all in the `plot`, module, can you rename them?

`silhouette_plot` -> `silhouette`
`silhouette_plot_from_results` -> `silhouette_from_results` 

Also, please include 0.8.3 as the version when this plots became available, in case anyone is using an older version. This way they'll know they have to update, you can add a `.. versionadded::` in a `Notes` section in the plot's docstring

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

FYI: @idomic

**Comment by neelasha23** [comment]
Point 1: Should I add it to the contribution guidelines doc?

**Comment by edublancas** [comment]
Yes, please include both guidelines in the contributing doc!

**Comment by neelasha23** [comment]
All the examples in the contributing doc have the function name as `plot_something`.. this might be confusing. Should we change these names also?

**Comment by edublancas** [comment]
yeah, my bad. thanks for spotting it. please update it!

**Comment by neelasha23** [comment]
Addressed in [PR](https://github.com/ploomber/sklearn-evaluation/pull/87)

**Comment by edublancas** [comment]
thanks for closing this. FYI: when opening PRs you can put "closes #{number}" and GitHub will automatically close the issue when the PR is merged. this way there's no need to manually close issues

**Comment by neelasha23** [comment]
sure will do it going forward!
