### ISSUE TITLE
Liks to "Edit on GitHub" are broken for some doc pages

### ISSUE THREAD

**Issue by RodolfoFerro** [ploomber/sklearn-evaluation#90]
![Screen Shot 2022-12-07 at 12 03 27](https://user-images.githubusercontent.com/8453749/206261286-326f978d-74fd-4fa7-acad-e8ad9fc4f0e2.png)

If you click on the "Edit on GitHub" link, it takes you to a 404 GitHub page for some doc pages:

![Screen Shot 2022-12-07 at 12 03 39](https://user-images.githubusercontent.com/8453749/206261354-9165aa6e-39c5-4ffc-82a7-f020ec88d9c5.png)

**Comment by edublancas** [comment]
thanks for reporting this! we are moving to jupyterbook, so I'm closing this
