### ISSUE TITLE
Cryptic error for feature importance

### ISSUE THREAD

**Issue by idomic** [ploomber/sklearn-evaluation#97]
```
from sklearn import svm
from sklearn_evaluation import plot

X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
plot.feature_importances(clf)
```

gives the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [13], line 1
----> 1 plot.feature_importances(clf)

File ~/opt/miniconda3/lib/python3.9/site-packages/sklearn_evaluation/telemetry.py:38, in SKLearnEvaluationLogger.log.<locals>.wrapper.<locals>.inner(*args, **kwargs)
     35     metadata['exception'] = str(e)
     36     telemetry.log_api(
     37         'sklearn-evaluation-error', metadata=metadata)
---> 38     raise e
     40 return result

File ~/opt/miniconda3/lib/python3.9/site-packages/sklearn_evaluation/telemetry.py:33, in SKLearnEvaluationLogger.log.<locals>.wrapper.<locals>.inner(*args, **kwargs)
     30 telemetry.log_api('sklearn-evaluation', metadata=metadata)
     32 try:
---> 33     result = func(*args, **kwargs)
     34 except Exception as e:
     35     metadata['exception'] = str(e)

File ~/opt/miniconda3/lib/python3.9/site-packages/sklearn_evaluation/plot/classification.py:254, in feature_importances(data, top_n, feature_names, orientation, ax)
    249     raise ValueError('data is needed to plot feature importances. '
    250                      'When plotting using the evaluator you need to pass '
    251                      'an estimator ')
    253 # If no feature_names is provided, assign numbers
--> 254 res = compute.feature_importances(data, top_n, feature_names)
    256 ax = bar.plot(res.importance,
    257               orientation,
    258               res.feature_name,
    259               error=None if not hasattr(res, 'std_') else res.std_)
    260 ax.set_title("Feature importances")

File ~/opt/miniconda3/lib/python3.9/site-packages/sklearn_evaluation/compute.py:49, in feature_importances(data, top_n, feature_names)
     46     std = None
     48 # get the number of features
---> 49 n_features = len(imp)
     51 # check that the data has the correct format
     52 if top_n and top_n > n_features:

TypeError: len() of unsized object
```

**Comment by edublancas** [comment]
The problem is that `plot.feature_importances` expects data in the first argument, not a model object; so we should check that  we can run `len` on the first argument; if not, we should throw a more informative error like:

```
Data is an object of type {type} but expected some data-like argument
```

**Comment by edublancas** [comment]
nevermind, I look at the source code, our feature_importances function *should work* with models (that follow sklearn's API and data): https://github.com/ploomber/sklearn-evaluation/blob/557ea67ac30afa01407fa0f30213325b16f61c20/src/sklearn_evaluation/compute.py#L5

so I'm unsure why it's broken - I'm guessing that SVC doesn't have a feature_importances_ attribute, so we need to investigate more

**Comment by DanBasson** [comment]
Hi,

I'm new to this group and would like to contribute.
Feature Importance is available only for trees-like models.
In this case maybe we could use "permutation feature importance", which has better properties then the "regular" 
feature importance, according to Jeremy Howards's article [here](https://explained.ai/rf-importance/)
In addition, it's applicable to all ML models and is also available in scikit-learn -[here]( https://scikit-learn.org/stable/auto_examples/inspection/plot_permutation_importance.html#sphx-glr-auto-examples-inspection-plot-permutation-importance-py)
I think that the default method should be the same, but when a model does not have a feature_importance property, use the 
"permutation feature importance", and add a message.
what do you think?

**Comment by edublancas** [comment]
> I think that the default method should be the same, but when a model does not have a feature_importance property, use the

yes. this makes sense. feel free to open a PR!
